version: '3.1'

services:
  et-backend:
    container_name: et-backend1
    build: https://github.com/Masha-Korol/EventTrackerNode.git
    ports:
      - "7010:9000"
    depends_on:
      - et-mongo

  et-frontend:
    container_name: et-frontend1
    build: https://github.com/Masha-Korol/EventTrackerVue.git
    ports:
      - "8080:8080"
    depends_on:
      - et-backend

  et-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: fh348a
      MONGO_INITDB_DATABASE: event-tracker
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: fh348a
      ME_CONFIG_MONGODB_URL: mongodb://admin:fh348a@mongo:27017/
